name: Build Wheels
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.0
        with:
            # Point to the subdirectory containing your setup/pyproject file
          package-dir: calc_tb_sounder
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y epel-release && 
            yum install -y netcdf-devel hdf5-devel wget m4 &&
            wget https://github.com &&
            tar -xf v4.6.1.tar.gz && cd netcdf-fortran-4.6.1 &&
            export CPPFLAGS="-I/usr/include" LDFLAGS="-L/usr/lib64" &&
            ./configure --prefix=/usr --disable-shared &&
            make -j$(nproc) && make install && cd ..
          
          CIBW_ENVIRONMENT: >
            PKG_CONFIG_PATH=/usr/lib/pkgconfig \
            FC=gfortran \
            FFLAGS="-I/usr/include" \
            FCFLAGS="-I/usr/include"

          CIBW_BEFORE_BUILD: pip install numpy

          CIBW_SKIP: cp39-*